### ISSUE TITLE
Top画面作成

### ISSUE THREAD

**Issue by purotoko321** [purotoko321/housework_sharing#5]
## やること
+ top画面の作成
+ 作成後、テスト書いて確認

**Comment by purotoko321** [comment]
vueを導入
```
bundle exec rails webpacker:install:vue
```

**Comment by purotoko321** [comment]
vuetifyとvuetifyアイコンをインストール
```
yarn add vuetify
docker-compose run web yarn add @mdi/font
```

**Comment by purotoko321** [comment]
webpackerのコンパイルが遅くてデバッグが辛い、、と感じて調べてみた
https://qiita.com/MoguraStore/items/ca80c99c5542898ec3b5
https://qiita.com/masarashi/items/6b437596c81a2c6347a4
公式
https://github.com/rails/webpacker/blob/5-x-stable/docs/docker.md

webpackerをコンテナにしたらコンパイルが速くなったが、、
ちょっとだけ表示できてたvueがロードエラーになった

**Comment by purotoko321** [comment]
https://github.com/rails/webpacker/issues/1540
参考にした。
結果としては https://github.com/rails/webpacker/blob/5-x-stable/docs/docker.md

dockerfileの記述が間違っていた。
vutifyが反映されたしwebpackも高速になったし嬉しい

**Comment by purotoko321** [comment]
解決したかと思いきや、webpackerが動かなくなってただけだった、、。
早とちりにも程がある。
https://github.com/rails/webpacker/issues/977
を参考に色々試している

**Comment by purotoko321** [comment]
https://qiita.com/terufumi1122/items/73da039e6fc90ee0a63f
これ試してみた。
---
多分別の原因でdbコンテナが消せなくなった

**Comment by purotoko321** [comment]
メッセージに以下が出ていたので、config/enviroment/development.rbにホワイトリストなるものを追加してみた
```
Cannot render console from 172.31.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
```
config/enviroment/development.rb
```
  # ホワイトリスト
  config.web_console.whitelisted_ips = "172.31.0.1" #追記
```

**Comment by purotoko321** [comment]
よく調べてみたらコンパイル時にエラーが出ていた
```
web_1 | [Webpacker] Compiling...

web_1 | [Webpacker] Compilation failed:

web_1 | /usr/local/bundle/gems/webpacker-5.4.0/lib/webpacker/runner.rb:13:in ``': No such file or directory - yarn (Errno::ENOENT)

web_1 | from /usr/local/bundle/gems/webpacker-5.4.0/lib/webpacker/runner.rb:13:in `initialize'

web_1 | from /usr/local/bundle/gems/webpacker-5.4.0/lib/webpacker/runner.rb:6:in `new'

web_1 | from /usr/local/bundle/gems/webpacker-5.4.0/lib/webpacker/runner.rb:6:in `run'

web_1 | from ./bin/webpack:17:in `block in <main>'

web_1 | from ./bin/webpack:16:in `chdir'

web_1 | from ./bin/webpack:16:in `<main>'
```
yarnがない？
```
docker-compose run web bundle list| grep yarn
```
してみたら確かにない

**Comment by purotoko321** [comment]
dokerfileにyarnをインストールする記述を書いて再度docker-compose up --build

そしたらdevtoolでこんなエラー出た
```
DevTools failed to load source map: Could not load content for http://localhost:3000/packs/js/application-f826770d917d8a37c1d8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
でもjs以下にファイルは生成されている、、、なぜ、、

**Comment by purotoko321** [comment]
https://qiita.com/undrthemt/items/52a557cb937d133b7140
上の記事と、記事内のリンクが良さそう。読んでみる
